version: "3.9"
services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elastic-search
    environment:
      - node.name=elastic-search
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false # Deshabilita la seguridad
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    container_name: kibana
    environment:
      - node.name=kibana
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    ports:
      - 5601:5601
    networks:
      - elastic
    depends_on:
      - elastic-search

volumes:
  data:
    driver: local
networks:
  elastic:
    driver: bridge
